export const postsData = [
  {
    id: 1,
    title: 'New Smartphone Model Released',
    content: 'A new smartphone model with advanced features has been released.',
    author: 'John Doe',
    datepublished: '2023-09-20',
    category: 'Mobile',
    links: ['https://example.com/news1'],
    thumbnail: 'https://example.com/thumbnail.jpg',
  },
  {
    id: 1,
    title: 'New Smartphone Model Released',
    content: 'A new smartphone model with advanced features has been released.',
    author: 'John Doe',
    datepublished: '2023-09-20',
    category: 'Mobile',
    links: ['https://example.com/news1'],
    thumbnail: 'https://example.com/thumbnail.jpg',
  },
  {
    id: 1,
    title: 'New Smartphone Model Released',
    content: 'A new smartphone model with advanced features has been released.',
    author: 'John Doe',
    datepublished: '2023-09-20',
    category: 'Mobile',
    links: ['https://example.com/news1'],
    thumbnail: 'https://example.com/thumbnail.jpg',
  },
  {
    id: 1,
    title: 'New Smartphone Model Released',
    content: 'A new smartphone model with advanced features has been released.',
    author: 'John Doe',
    datepublished: '2023-09-20',
    category: 'Mobile',
    links: ['https://example.com/news1'],
    thumbnail: 'https://example.com/thumbnail.jpg',
  },
  {
    id: 1,
    title: 'New Smartphone Model Released',
    content: 'A new smartphone model with advanced features has been released.',
    author: 'John Doe',
    datepublished: '2023-09-20',
    category: 'Mobile',
    links: ['https://example.com/news1'],
    thumbnail: 'https://example.com/thumbnail.jpg',
  },
  {
    id: 1,
    title: 'New Smartphone Model Released',
    content: 'A new smartphone model with advanced features has been released.',
    author: 'John Doe',
    datepublished: '2023-09-20',
    category: 'Mobile',
    links: ['https://example.com/news1'],
    thumbnail: 'https://example.com/thumbnail.jpg',
  },
];

export const categoriesData = [
  {
    id: '1',
    name: 'Technology',
  },
  {
    id: '2',
    name: 'Tips & Tricks',
  },
  {
    id: '3',
    name: 'AI',
  },
  {
    id: '4',
    name: 'Programming',
  },
];
